name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub (or another registry)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Set up Docker Compose
    - name: Set up Docker Compose
      uses: docker/compose-action@v2

    # Step 4: Build the services using Docker Compose
    - name: Build Docker Compose Services
      run: docker compose -f docker-compose.yml build

    # Step 5: Push the Docker image
    - name: Push Docker Image
      run: |
        docker tag my-python-app <your-repo>/my-python-app:latest
        docker push <your-repo>/my-python-app:latest

    # Optional: Deploy to Kubernetes or another service
    # Uncomment and customize based on your deployment needs
    # - name: Deploy to Kubernetes
    #   run: kubectl apply -f k8s/deployment.yaml
