name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Compose
    - name: Set up Docker Compose
      uses: docker/compose-action@v2

    # Step 3: Build the services using Docker Compose
    - name: Build Docker Compose Services
      run: docker compose -f docker-compose.yml build

    # # Step 4: Run the tests
    # - name: Run Tests
    #   run: docker compose -f docker-compose.yml run --rm app python -m unittest discover -s src/tests

    # Step 5: Clean up resources
    - name: Clean up
      run: docker compose down
