name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Install Docker Compose
    - name: Install Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # Step 4: Build the services using Docker Compose
    - name: Build Docker Compose Services
      run: docker-compose -f docker-compose.yml build

    # # Step 5: Run the tests
    # - name: Run Tests
    #   run: docker-compose -f docker-compose.yml run --rm app python -m unittest discover -s src/tests

    # Step 6: Clean up resources
    - name: Clean up
      run: docker-compose down
